### ISSUE TITLE
Use `ROOT_CONTAINER` to avoid patching together huge Dockerfile

### ISSUE THREAD

**Issue by maresb** [ChristophSchranz/gpu-docker-stacks#1]
Hi Christoph, `BASE_CONTAINER` was the wrong variable name.  I believe that `ROOT_CONTAINER` will behave as we expect.

https://github.com/jupyter/docker-stacks/pull/1001#issuecomment-586887235

**Comment by ChristophSchranz** [comment]
As the requested, and merged, solution in https://github.com/jupyter/docker-stacks/pull/1001#issuecomment-586887235 seems not to work properly, I continued with the variant of patching together a single Dockerfile. This fork is therefore a solution with the same goal.

The solution right now seems to be okay and the Dockerhub image can be found [here](https://hub.docker.com/repository/docker/cschranz/gpu-jupyter/general).
