### ISSUE TITLE
Try to include docker-stacks as submodule?

### ISSUE THREAD

**Issue by maresb** [ChristophSchranz/gpu-docker-stacks#2]
I think this would allow parallel development.  In the current situation, docker-stacks will receive more commits, and then your repo will be out-of-date.

I personally don't have any experience with submodules, but it's something I need to learn.

**Comment by ChristophSchranz** [comment]
That's a nice idea. My first trial was actually [gpu-jupyter](https://github.com/ChristophSchranz/gpu-jupyter), what I will update to the automatic Dockerfile generation.

**Comment by maresb** [comment]
What's the difference between the two repos? Is this your personal, and the other is like the master branch?

**Comment by ChristophSchranz** [comment]
I'm not sure whether [gpu-docker-stacks](https://github.com/ChristophSchranz/gpu-docker-stacks) will be merged into the master docker-stacks, as they say that they want to let the images compact and PyTorch, Tensorflow etc. is not that small. So I have a mirrored repository that is master.

**Comment by ChristophSchranz** [comment]
However, I want to update both repos.

**Comment by maresb** [comment]
Ah, I meant to ask what is the difference between gpu-docker-stacks and gpu-jupyter?

**Comment by ChristophSchranz** [comment]
The only difference is the structure: gpu-docker-stacks, as a fork, has an additional directory called gpu-notebooks.
This directory is similar to gpu-jupyter, but this repo uses the master docker-stacks as a submodule within the `.build` directory.

**Comment by maresb** [comment]
I'm really confused because I can't find any submodules in this repo.  Submodules show up on GitHub as a directory with " @ commit-id" at the end, as in [this example](https://github.com/githubtraining/example-dependency).  On my side, it looks like this is still just a fork of jupyter/docker-stacks.

**Comment by ChristophSchranz** [comment]
Thanks @maresb for the hint. I've added it with [this](https://github.com/iot-salzburg/gpu-jupyter/commit/c9a934abaf2198d8d38e5f4ce4628ddb6d77f8bf) commit.

Note also that I may end to develop on this fork and will focus on the [gpu-jupyter(https://github.com/iot-salzburg/gpu-jupyter) repo (with docker-stacks as submodule), as mentioned in this [chat](https://github.com/jupyter/docker-stacks/pull/1023)
