### ISSUE TITLE
Set up build on DockerHub

### ISSUE THREAD

**Issue by maresb** [ChristophSchranz/gpu-docker-stacks#3]
With an account on DockerHub, you can very easily link it to your GitHub account and select a Dockerfile to automatically render.  This way, I could use your gpu-docker-stacks in my project without having to build it myself.  I just start my own Dockerfile with `FROM ChristophSchranz/gpu-notebook`, install my own packages on top, and that's it!

I think I'll need this in the near future, so this would save me tons of work!  :)

**Comment by ChristophSchranz** [comment]
Done in [cschranz/gpu-jupyter](https://hub.docker.com/r/cschranz/gpu-jupyter).

It is my first image on dockerhub, so I'm open to more suggestions and advice! :)

**Comment by maresb** [comment]
Nice!!! Congratulations on your first Docker Hub image. I'm very glad that this exists now, so thank you very much!

**Comment by ji3g4m6zo6** [comment]
I got an error by running `docker run cschranz/gpu-jupyter:latest`.
`[FATAL tini (6)] exec start-notebook.sh failed: Permission denied`

**Comment by ChristophSchranz** [comment]
Hi @ji3g4m6zo6 ,
yes that's true, there was a permission exception and the commit 519551b7575c0dcf2a8d897cc3b1f73ba5a6e4e8 fixes the permission of the build files to 755. Please let me know if this works for you. It does work for me on Ubuntu.

**Comment by ji3g4m6zo6** [comment]
Hello @ChristophSchranz ,
I have successfully run the new docker image.

Pytorch work with GPU but tensorflow seems can't.

![GPU](https://i.imgur.com/lylQwqH.png)

**Comment by ChristophSchranz** [comment]
Hi @ji3g4m6zo6 ,
I think this helps you!
![image](https://user-images.githubusercontent.com/16668897/75222182-e74b9f00-57a3-11ea-9ce4-d72b3fdfb583.png)
 Let me know if this works!
